# Generated by Django 4.0.4 on 2022-04-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
    ]
