# Generated by Django 4.0.4 on 2022-04-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_imagen_producto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
