# Generated by Django 4.0.4 on 2022-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(blank=True, default=0, null=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
