# Generated by Django 4.0.4 on 2022-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='plan',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
