# Generated by Django 4.0.4 on 2022-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
